create table chamado (id integer not null auto_increment, primary key (id)) engine=InnoDB;
create table classepermissao (id integer not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table codigo (id integer not null auto_increment, codigo varchar(255), telefone varchar(255), primary key (id)) engine=InnoDB;
create table empresa (id integer not null auto_increment, bairro varchar(255), cep varchar(255), cidade varchar(255), complemento varchar(255), cpfoucnpj varchar(255), editar bit, email varchar(255), logradouro varchar(255), naturezapessoa varchar(255), nomecontato varchar(255), numero varchar(255), razaosocial varchar(255), status bit, telefone varchar(255), tenant_id integer, uf varchar(255), valor decimal(19,2), whats varchar(255), primary key (id)) engine=InnoDB;
create table log_sistema (id integer not null auto_increment, comando varchar(255), datagravacao datetime, loginusuario varchar(255), status bit, chamado_id integer not null, empresa_id integer not null, maquina_id integer not null, molde_id integer not null, operador_id integer not null, producao_id integer not null, produto_id integer not null, tenant_id integer, usuario_id integer not null, primary key (id)) engine=InnoDB;
create table maquina (id integer not null auto_increment, nome varchar(255), numero integer, peso varchar(255), tenant_id integer, primary key (id)) engine=InnoDB;
create table molde (id integer not null auto_increment, nome varchar(255), sku varchar(255), status bit, produto_id integer, tenant_id integer, primary key (id)) engine=InnoDB;
create table molde_maquina (status bit, molde_id integer not null, maquina_id integer not null,  primary key (maquina_id, molde_id)) engine=InnoDB;
create table operador (id integer not null auto_increment, nome varchar(255), status bit, tenant_id integer, primary key (id)) engine=InnoDB;
create table permissao (id integer not null auto_increment, descricao varchar(255), classepermissao_id integer, primary key (id)) engine=InnoDB;
create table producao (id integer not null auto_increment, dataprevicao datetime(6), dataproducao datetime(6), horafinal integer, horainicio integer, obs varchar(255), perda integer, piguimento varchar(255), quantidade integer, tempomaquina integer, lote varchar(255), maquina_id integer, operador_id integer, produto_id integer, tenant_id integer, primary key (id)) engine=InnoDB;
create table produto (id integer not null auto_increment, nome varchar(255), sku varchar(255), tenant_id integer, primary key (id)) engine=InnoDB;
create table tenant (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table usuario (id integer not null auto_increment, gtenantativo integer, login varchar(255), nome varchar(255), senha varchar(255), status bit, tenantativo integer, primary key (id)) engine=InnoDB;
create table usuario_permissao (id_usuario integer not null, id_permissao integer not null) engine=InnoDB;
create table usuario_empresa (empresapadrao bit, tenant_id integer, id_empresa integer not null, id_usuario integer not null, primary key (id_empresa, id_usuario)) engine=InnoDB;
alter table empresa add constraint UK_ow6ddx531a4abnwv6eah7h3k7 unique (cpfoucnpj);
alter table log_sistema add constraint FKh53k6hag9ey8n4vlt5e99fdej foreign key (chamado_id) references chamado (id);
alter table log_sistema add constraint FKdtxgdxwvuxbb45995iirr9ase foreign key (empresa_id) references empresa (id);
alter table log_sistema add constraint FKosx886mtg29wj5npaoolbg7o7 foreign key (maquina_id) references maquina (id);
alter table log_sistema add constraint FK49c0n0l8i4gyk9aey5cfujtyq foreign key (molde_id) references molde (id);
alter table log_sistema add constraint FKco03o6b30pdv6a13ydgt6tli5 foreign key (operador_id) references operador (id);
alter table log_sistema add constraint FKl5d5lgqi447yxtc4hlytvu1gy foreign key (producao_id) references producao (id);
alter table log_sistema add constraint FKci3i8bv71ec8vkfgbjgwpjily foreign key (produto_id) references produto (id);
alter table log_sistema add constraint FK70ecb2jvl5xk791a9ybtw1dsv foreign key (tenant_id) references tenant (id);
alter table log_sistema add constraint FKsltyfd8mjygt5amoo95i5p9iw foreign key (usuario_id) references usuario (id);
alter table maquina add constraint FKardd98k32ptx8q2iu9q1d6x2 foreign key (tenant_id) references tenant (id);
alter table molde add constraint FKn2vn8y1e3rcurb5aqxsin3gwy foreign key (produto_id) references produto (id);
alter table molde add constraint FKmkvgksuouva5f66b7u93u64dj foreign key (tenant_id) references tenant (id);
alter table molde_maquina add constraint FK8scxnc3kbpxbvr3r3613c61cw foreign key (molde_id) references molde (id);
alter table molde_maquina add constraint FK88xrqx8f4njrv98dg82q3r13m foreign key (maquina_id) references maquina (id);
alter table operador add constraint FKgejkr84ssg0j1yonlj09xq068 foreign key (tenant_id) references tenant (id);
alter table permissao add constraint FKdiyasfskbnh46lmx2ywloji0d foreign key (classepermissao_id) references classepermissao (id);
alter table producao add constraint FKn282yyqev4v7p8aq2jfdkf0ki foreign key (maquina_id) references maquina (id);
alter table producao add constraint FKcuqu33y1u0oe3741b0poxua7x foreign key (operador_id) references operador (id);
alter table producao add constraint FK3amh60cn20xwcnwgcoqimcwnh foreign key (produto_id) references produto (id);
alter table producao add constraint FKgmo5a48orha5m62ir53sphak2 foreign key (tenant_id) references tenant (id);
alter table produto add constraint FK9lpb3f1r5xbcc0fcex0ubs0i6 foreign key (tenant_id) references tenant (id);
alter table usuario_permissao add constraint FKjvcxjnrmdhdv6eti5d7svm5xw foreign key (id_permissao) references permissao (id);
alter table usuario_permissao add constraint FKbo8hww1whbpxq8ancjokhnfds foreign key (id_usuario) references usuario (id);
alter table usuario_empresa add constraint FKkicrvlg5cwo9w2xi83xrq4ver foreign key (id_empresa) references empresa (id);
alter table usuario_empresa add constraint FK62hh8xjf2yjsncl8ti6vxjm7h foreign key (id_usuario) references usuario (id);